NHNT_G08/NHNT_G08/Controllers/BaiDangController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NHNT_G08.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NHNT_G08.Controllers
{
    public class BaiDangController : Controller
    {
        private readonly NHNTContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public BaiDangController(NHNTContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public IActionResult ThemBaiDang()
        {
            var quyen = checkQuyen();
            if (quyen)
            {
                ViewData["Title"] = "Thêm Bài Đăng";
                ViewData["Action"] = "ThemBaiDang";
                ViewData["Btn_Value"] = "Tạo Mới";
                return View();
            }
            TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public IActionResult ThemBaiDang([Bind("tenPhong, diaChi, giaPhong, giaDien, giaNuoc, soDienThoai, chiTietPhong, trangThaiBaiDang, trangThaiPhong, maTaiKhoan,files, dienTich")] Phong phong)
        {
            var quyen = checkQuyen();
            if (quyen)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(phong);
                    _context.SaveChanges();
                    var maPhong = phong.maPhong;
                    if (phong.files.Count > 0)
                    {
                        foreach (var file in phong.files)
                        {

                            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/anhphong_" + maPhong);

                            //create folder if not exist
                            if (!Directory.Exists(path))
                                Directory.CreateDirectory(path);


                            string fileNameWithPath = Path.Combine(path, file.FileName);

                            using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                            {
                                file.CopyTo(stream);
                            }
                            HinhAnh anh = new HinhAnh();
                            anh.maPhong = maPhong;
                            anh.duongDan = file.FileName;
                            _context.tblHinhAnh.Add(anh);
                        }
                        _context.SaveChanges();
                    }

                    return RedirectToAction("BaiDaDang");
                }
                return View(phong);
            }
            TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
            return RedirectToAction("Index", "Login");     
        }

        [HttpGet]
        public IActionResult SuaBaiDang(Phong phong)
        {
            var quyen = checkQuyen();
            if (quyen)
            {
                ViewData["Title"] = "Sửa Bài Đăng";
                ViewData["Btn_Value"] = "Sửa";
                ViewData["Action"] = "SuaBaiDang";
                return View("ThemBaiDang");
            }
            TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public IActionResult SuaBaiDang(Phong phong, string unusedValue = "")
        {
            var quyen = checkQuyen();
            if (quyen)
            {
                if (ModelState.IsValid)
                {
                    _context.Update(phong);
                    var listAnh = _context.tblHinhAnh.Where(p => p.maPhong == phong.maPhong).ToList();
                    _context.tblHinhAnh.RemoveRange(listAnh);
                    _context.SaveChanges();
                    var maPhong = phong.maPhong;
                    if (phong.files.Count > 0)
                    {
                        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/anhphong_" + maPhong);

                        //create folder if not exist
                        if (!Directory.Exists(path))
                            Directory.CreateDirectory(path);
                        else
                        {
                            Directory.Delete(path, true);
                            Directory.CreateDirectory(path);
                        }

                        foreach (var file in phong.files)
                        {
                            string fileNameWithPath = Path.Combine(path, file.FileName);

                            using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                            {
                                file.CopyTo(stream);
                            }
                            HinhAnh anh = new HinhAnh();
                            anh.maPhong = maPhong;
                            anh.duongDan = file.FileName;
                            _context.tblHinhAnh.Add(anh);
                        }
                        _context.SaveChanges();
                    }

                    return RedirectToAction("BaiDaDang");
                }
                return View(phong);
            }
            TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
            return RedirectToAction("Index", "Login");  
        }

        [HttpPost]
        public string XoaBaiDang([FromForm] int maPhong)
        {
            try
            {
                var phong = _context.tblPhong.Find(maPhong);
                var hinhAnhPhong = _context.tblHinhAnh.Where(p => p.maPhong == maPhong).ToList();
                _context.tblPhong.Remove(phong);
                _context.tblHinhAnh.RemoveRange(hinhAnhPhong);
                _context.SaveChanges();
                return "Xóa Thành Công";
            }
            catch
            {
                return "Xảy Ra Lỗi Trong Quá Trình Xóa";
            }
        }


        [HttpGet]
        public IActionResult BaiDangDaDanhGia(int? pageIndex)
        {
            var quyen = checkQuyen();
            if (quyen)
            {
                int pageSize = 12;
                int maTaiKhoan = Convert.ToInt32(_httpContextAccessor.HttpContext.Session.GetString("maTaiKhoan"));
                var listMaPhong = _context.tblDanhGiaPhong.Where(p => p.maTaiKhoan == maTaiKhoan).Select(p => p.maPhong).ToList();
                var listPhong = _context.tblPhong.Where(p => listMaPhong.Contains(p.maPhong)).ToList();
                foreach (var phong in listPhong)
                {
                    var soSao = _context.tblDanhGiaPhong.Where(p => p.maPhong == phong.maPhong && p.maTaiKhoan == maTaiKhoan).Select(p => p.soSao).First();
                    phong.soSaoTrungBinh = soSao;
                }
                return View(Pagination<Phong>.Create(listPhong, pageIndex ?? 1, pageSize));
            }
            TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
            return RedirectToAction("Index", "Login");
        }

        List<Phong> LayThongTinNguoiDang(List<Phong> listPhong)
        {
            foreach (var phong in listPhong)
            {
                var taiKhoan = _context.tblTaiKhoan.First(p => p.maTaiKhoan == phong.maTaiKhoan);
                phong.tenNguoiDang = taiKhoan.hoTenNguoiDung;
            }
            return listPhong;
        }

        [HttpGet]
        public IActionResult BaiDaDang()
        {
            var quyen = checkQuyen();
            if (quyen)
            {
                var listPhong = _context.tblPhong.Where(p => p.maTaiKhoan == Convert.ToInt32(_httpContextAccessor.HttpContext.Session.GetString("maTaiKhoan"))).ToList();
                LayThongTinNguoiDang(listPhong);
                return View(listPhong);
            }
            TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
            return RedirectToAction("Index", "Login");
            
        }

        public bool checkQuyen()
        {
            var maTaiKhoan = _httpContextAccessor.HttpContext.Session.GetString("maTaiKhoan");
            if (maTaiKhoan != null)
            {
                return true;
            }
            return false;
        }
    }
}

NHNT_G08/NHNT_G08/Controllers/QuanLyBaiDangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using NHNT_G08.Models;

namespace NHNT_G08.Controllers
{
    public class QuanLyBaiDangController : Controller
    {
        
        private readonly NHNTContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public QuanLyBaiDangController(NHNTContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: bài đăng
        public async Task<IActionResult> Index(string timP, string timND)
        {
            var maTaiKhoan = _httpContextAccessor.HttpContext.Session.GetString("maTaiKhoan");
            if (maTaiKhoan != null && Convert.ToInt32(maTaiKhoan) == 1) {
                var listBD = await _context.tblPhong.ToListAsync();
                foreach (var phong in listBD)
                {
                    var taiKhoan = _context.tblTaiKhoan.First(p => p.maTaiKhoan == phong.maTaiKhoan);
                    phong.tenNguoiDang = taiKhoan.hoTenNguoiDung;
                }
                if (!String.IsNullOrEmpty(timP))
                {
                    listBD = listBD.Where(s => s.tenPhong.Contains(timP)).ToList();

                }

                if (!String.IsNullOrEmpty(timND))
                {

                    listBD = listBD.Where(s => s.tenNguoiDang.Contains(timND)).ToList();
                }

                return View(listBD);
            }
            else if (maTaiKhoan == null)
            {
                TempData["ThongBao"] = "Bạn Cần Đăng Nhập Để Thực Hiện Tác Vụ Này";
                return RedirectToAction("Index", "Login");
            }
            else
            {
                TempData["ThongBao"] = "Bạn Không Có Quyền Thực Hiện Tác Vụ Này";
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public async Task<bool> duyetBaiDang(int id)
        {
            try
            {
                var phong = _context.tblPhong.Where(p=>p.maPhong == id).First();
                phong.trangThaiBaiDang = "duyệt";
                _context.tblPhong.Update(phong);
                await _context.SaveChangesAsync();
                return true;
            } catch
            {
                return false;
            }
        }


        [HttpPost]
        public async Task<IActionResult> xoaBaiDang(int id)
        {
            
                //var phong = _context.tblPhong.Where(p => p.maPhong == id).First();
                var phong = await _context.tblPhong.FindAsync(id);
                _context.tblPhong.Remove(phong);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


        }
    }
}

NHNT_G08/NHNT_G08/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using NHNT_G08.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using System.IO;

namespace NHNT_G08.Controllers
{
    [Route("[controller]")]
    public class RegisterController : Controller
    {
        private readonly NHNTContext _context;
        public RegisterController(NHNTContext context)
        {

            _context = context;
        }


        [Route("Index")]
        public IActionResult Index()
        {
            return View("~/Views/Account/Register.cshtml");
        }

        [HttpPost]
        public async Task<ActionResult> Register(TaiKhoan model, IFormFile anhDaiDien)
        {

            var errorMessage = ValidateRegistration(model);
            if (errorMessage != null)
            {
                ViewBag.loi = errorMessage;
                return View("~/Views/Account/Register.cshtml", model);
            }

            // Thêm dữ liệu mới vào cơ sở dữ liệu
            model.maDmTaiKhoan = 2;
            model.trangThai = "Hoạt Động";

            if (anhDaiDien != null && anhDaiDien.Length > 0)
            {
                // Lưu tệp tin vào thư mục trong dự án
                // string oldfile="wwwroot/img/anhdaidien" + model.anhDaiDien;
                // if(System.IO.File.Exists(oldfile)){
                //     System.IO.File.Delete(oldfile);
                // }
                string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/anhdaidien");
                string uniqueFileName = model.tenDangNhap +".jpg";
                string filePath = Path.Combine(uploadsPath, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await anhDaiDien.CopyToAsync(fileStream);
                }
                // Lưu tên tệp tin vào đối tượng taiKhoan
                model.anhDaiDien = uniqueFileName;
            }
            else{
                ViewBag.loi = "lỗi ảnh" + model.anhDaiDien;
                return View("~/Views/Account/Register.cshtml", model);
            }
            /*if (anh != null && anh.Length > 0)
            {
                try
                {
                    // Mã để lưu ảnh vào thư mục
                    string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/anhdaidien");
                    if (!Directory.Exists(uploadsPath))
                    {
                        Directory.CreateDirectory(uploadsPath);
                    }
                    model.anhDaiDien = model.tenDangNhap + ".jpg";
                    string filePath = Path.Combine(uploadsPath, model.anhDaiDien);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await anh.CopyToAsync(fileStream);
                    }
                    // Lưu tên tệp tin vào đối tượng taiKhoan
                }
                catch (Exception ex)
                {
                    ViewBag.loi = "lỗi ảnh" + model.anhDaiDien;
                    return View("~/Views/Account/Register.cshtml", model);
                }
                // string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img/anhdaidien");
                // string uniqueFileName = model.tenDangNhap + ".jpg";
                // string filePath = Path.Combine(uploadsPath, uniqueFileName);
                // using (var fileStream = new FileStream(filePath, FileMode.Create))
                // {
                //     await anhDaiDien.CopyToAsync(fileStream);
                // }
                // Lưu tên tệp tin vào đối tượng taiKhoan
                // model.anhDaiDien = uniqueFileName;
            }*/
            // else{
            //     ViewBag.loi = "lỗi ảnh" + model.anhDaiDien;
            //     return View("~/Views/Account/Register.cshtml", model);
            // }
            _context.tblTaiKhoan.Add(model);
            _context.SaveChanges();
            TempData["ThongBao"] = "Đăng Ký Thành Công";
            // Redirect đến trang đăng nhập hoặc trang chủ
            return RedirectToAction("Index", "Login", model);
            

        }
        private string ValidateRegistration(TaiKhoan model)
        {
            if (!ModelState.IsValid)
            {
                return "Vui lòng nhập đủ thông tin!";
            }
            if (!int.TryParse(model.soDienThoai, out _))
            {
                return "Số điện thoại không đúng định dạng!";
            }
            if (_context.tblTaiKhoan.Any(u => u.tenDangNhap == model.tenDangNhap))
            {
                return "Tài khoản đã tồn tại, vui lòng thay đổi Tên đăng nhập!";
            }
            return null;
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("Error")]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

NHNT_G08/NHNT_G08/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   
    <link rel="stylesheet" href="~/font-awesome-6-offline/css/all.css" />
    @RenderSection("Style")
    @using Microsoft.AspNetCore.Http
    @inject IHttpContextAccessor httpContextAccessor
</head>
<body>
    <div id="web">
        <header class="header">
            <!-- menu -->
            <div class="header_menu">
                <a href="index.html"><img src="./assets/img/Logo200.png" alt="" class="logo"></a>
                <ul class="menu_list">
                    <li class="menu_list-item">
                        <a asp-action="Index" asp-controller="Home" class="menu_list-item-link menu_list-item-nth1">TRANG CHỦ</a>
                        
                    </li>
                    <li class="menu_list-item">
                        <a asp-action="BaiDaDang" asp-controller="BaiDang" class="menu_list-item-link">BÀI ĐĂNG</a>
                        
                    </li>
                    <li class="menu_list-item">
                        <a asp-action="BaiDangDaDanhGia" asp-controller="BaiDang" class="menu_list-item-link">ĐÁNH GIÁ</a>
                    </li>
                    
                        <li class="menu_list-item">
                        <a href="@Url.Action("Index", "Register")" class="menu_list-item-link dangki">ĐĂNG KÍ</a>
                        </li>
                        <li class="menu_list-item">
                            <a href="@Url.Action("Index", "Login")" class="menu_list-item-link dangnhap">ĐĂNG NHẬP</a>
                        </li>
                    @if (httpContextAccessor.HttpContext.Session.GetString("hoTenNguoiDung") != null)
                    {                    
                    <div class="menu_list-hot">                        
                        <p>
                            
                             
                            <a href="@Url.Action("Index", "Account")" class="tenDangNhap control_account">
                                <img src="@if(httpContextAccessor.HttpContext.Session.GetString("anhDaiDien") != null) {@httpContextAccessor.HttpContext.Session.GetString("anhDaiDien")}" alt="" style="width:40px;height: 40px; margin-top:-10px; border-radius: 50%">
                                <span> @httpContextAccessor.HttpContext.Session.GetString("hoTenNguoiDung") </span>
                                </a>
                            <a href="@Url.Action("Index", "ChangePass")" class="changepass">| Đổi mật khẩu</a> 
                            <a href="@Url.Action("Logout", "Login")" class="dangxuat">| Đăng xuất</a>       
                        </p>
                        @if(httpContextAccessor.HttpContext.Session.GetString("maDmTaiKhoan") == "1"){
                            
                        <p style="margin-left: 52px;">
                            <a asp-controller="QuanLyTaiKhoan" asp-action="Index" class="control_account">Quản lý tài khoản |</a>
                            <a asp-controller="QuanLyBaiDang" asp-action="Index" class="control_account">Quản lý bài đăng</a>
                        </p>
                        }
                    </div>
                    }
                </ul>
            </div>
            

        </header>

        @RenderBody()

        <footer>
            <hr>
            <div class="grid footer">
                <div class="grid_col_3 footer_col_1">
                    <h3 class="footer_col_1-title">NGÂN HÀNG NHÀ TRỌ G08</h3>
                    <p>Trụ sở chính :96 Định Công,Phương Liệt, Thanh Xuân, Hà Nội </p>
                    <p>Chi nhánh Hà Nội : 101 Nguyễn Hiền, Bách Khoa, Hai Bà Trưng, Hà Nội</p>
                    <p>Điện thoại : 0964 154 302 | Hotline: 1900 9876</p>
                    <p>Website : nhntg08.com.vn</p>
                    <p>Email: nhntg08@gmail.com</p>
                </div>

                <div class="grid_col_3 footer_col_1 grid_col_3-double">
                    <div>
                        <h3 class="footer_col_1-title">Khách hàng</h3>
                        <p>Chính sách đặt tour</p>
                        <p>Ý kiến khách hàng</p>
                        <p>Phiếu góp ý</p>

                    </div>
                    <div style="padding-left: 50px;">
                        <h3 class="footer_col_1-title">Chứng nhận</h3>
                        <img src="./assets/img/tem1.png" alt="">
                        <img src="./assets/img/tem2.png" alt="">
                    </div>
                </div>

                <div class="grid_col_3 footer_col_1">
                    <h3 class="footer_col_1-title">Thông tin khuyến mãi từ công ty</h3>
                    <p>Những dịch vụ tiện ích khác</p>
                    <p>Chăm sóc khách hàng chu đáo tận tình</p>
                    <p>Chúng tôi thấu hiểu từ bạn</p>
                </div>

            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>